// Generated by CoffeeScript 1.3.3
(function() {
  var Game;

  Game = require('../models/game');

  exports.index = function(req, res) {
    return Game.find().exec(function(err, games) {
      return res.render('index', {
        title: 'N-Gon Games LLC',
        games: games
      });
    });
  };

}).call(this);
