// Generated by CoffeeScript 1.3.3
(function() {
  var Game, ObjectId, Schema, mongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  ObjectId = Schema.ObjectId;

  Game = new Schema({
    cdnUrl: {
      type: String,
      required: true
    },
    name: {
      type: String,
      required: true
    },
    description: {
      type: String
    },
    genre: {
      type: ObjectId
    },
    views: {
      "default": 0
    }
  });

  module.exports = mongoose.model('game', Game);

}).call(this);
